[package]
name = "game-of-life"
version = "0.1.0"
authors = ["Craig Mayhew <craig@mayhew.io>"]
edition = "2018"

[dependencies.amethyst]
version = "0.15.0"
features = ["vulkan"]

[dependencies]
rand = "0.7.3"